---
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: openshift-mtv
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # Controller container resource limits
  controller_container_limits_cpu: 2000m
  controller_container_limits_memory: 2000Mi
  
  # Inventory container resource limits
  inventory_container_limits_memory: 2000Mi
  
  # Feature flags
  feature_ui_plugin: "true"
  feature_validation: "true"
  feature_volume_populator: "true"
