---
apiVersion: v1
kind: Namespace
metadata:
  name: trident
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: "Namespace for the NetApp Trident Operator"
