---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.trident.netapp.io
parameters:
  backendType: ontap-nas
  fsType: ext4
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
