---
apiVersion: v1
kind: Namespace
metadata:
  name: aap
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: "Namespace for Ansible Automation Platform"
