---
# Add Secondary Network Interface to VM for S2S VPN Access
#
# This YAML adds a second NIC to a VM to connect it to the windows-non-prod
# secondary network, which provides access to the Site-to-Site VPN subnets.
#
# Usage:
#   Replace VM_NAME with the actual VM name (e.g., nymsdv301, nymsdv312)
#   
#   oc patch vm VM_NAME -n windows-non-prod --type='json' \
#     -p "$(cat add-secondary-nic-to-vm.yaml)"
#
# The VM must be stopped before applying this patch.

- op: add
  path: /spec/template/spec/domain/devices/interfaces/-
  value:
    name: nic-2
    bridge: {}
    # Optional: Specify MAC address to avoid conflicts
    # macAddress: "02:00:00:10:04:0B"

- op: add
  path: /spec/template/spec/networks/-
  value:
    name: nic-2
    multus:
      networkName: windows-non-prod

---
# Network Details:
#
# NetworkAttachmentDefinition: windows-non-prod
# Namespace: windows-non-prod (also exists in openshift-mtv, vm-migrations)
# CIDR: 10.132.104.0/22
# Gateway: 10.132.104.1
# DNS: 10.132.104.2, 10.132.104.3
# IPAM: Whereabouts (dynamic allocation)
#
# Reserved Static IPs (in exclude list):
# - 10.132.104.1  - Gateway
# - 10.132.104.2  - DNS Server 1
# - 10.132.104.3  - DNS Server 2
# - 10.132.104.10 - NYMSDV297
# - 10.132.104.11 - NYMSDV301
# - 10.132.104.19 - NYMSDV312
# - 10.132.104.20 - NYMSQA428
# - 10.132.104.21 - NYMSQA429

---
# Complete Example: Add Secondary NIC to NYMSDV301

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: nymsdv301
  namespace: windows-non-prod
spec:
  template:
    spec:
      domain:
        devices:
          interfaces:
            - name: net-0
              masquerade: {}
            - name: net-1
              bridge: {}
            # Second NIC added here:
            - name: nic-2
              bridge: {}
      networks:
        - name: net-0
          pod: {}
        - name: net-1
          multus:
            networkName: default/vm-bridge
        # Second network added here:
        - name: nic-2
          multus:
            networkName: windows-non-prod

---
# Step-by-Step Process:

# 1. Stop the VM
# virtctl stop VM_NAME -n windows-non-prod

# 2. Apply the patch
# oc patch vm VM_NAME -n windows-non-prod --type='json' \
#   -p='[
#     {
#       "op": "add",
#       "path": "/spec/template/spec/domain/devices/interfaces/-",
#       "value": {
#         "name": "nic-2",
#         "bridge": {}
#       }
#     },
#     {
#       "op": "add",
#       "path": "/spec/template/spec/networks/-",
#       "value": {
#         "name": "nic-2",
#         "multus": {
#           "networkName": "windows-non-prod"
#         }
#       }
#     }
#   ]'

# 3. Start the VM
# virtctl start VM_NAME -n windows-non-prod

# 4. Verify the VM has 2 IPs
# oc get vmi VM_NAME -n windows-non-prod -o jsonpath='{.status.interfaces[*].ipAddress}' | tr ' ' '\n'

# 5. Configure static IP inside the VM (Windows PowerShell as Administrator):
# Get-NetAdapter
# New-NetIPAddress -InterfaceAlias "Ethernet 2" -IPAddress 10.132.104.XX -PrefixLength 22 -DefaultGateway 10.132.104.1
# Set-DnsClientServerAddress -InterfaceAlias "Ethernet 2" -ServerAddresses ("10.132.104.2", "10.132.104.3")
# New-NetRoute -InterfaceAlias "Ethernet 2" -DestinationPrefix "10.132.0.0/14" -NextHop 10.132.104.1
# New-NetRoute -InterfaceAlias "Ethernet 2" -DestinationPrefix "10.227.96.0/20" -NextHop 10.132.104.1
# Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
# Enable-NetFirewallRule -DisplayName "File and Printer Sharing (Echo Request - ICMPv4-In)"
