---
# ExternalSecret for VPN Certificates in linux-non-prod namespace
# Syncs same certificates used by windows-non-prod VPN from AWS Secrets Manager
# VPN Connection: vpn-059ee0661e851adf4
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn-certificates
  namespace: linux-non-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: vpn-certificates
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: ipsec-vpn-linux
          managed-by: external-secrets
  dataFrom:
  - extract:
      key: ROSA-NONPROD-VPN-Tunnel2-Certificates
