---
# IPSec Gateway VM for windows-non-prod CUDN (10.227.128.0/21)
# This VM replaces both the container VPN and separate gateway VM
# It runs Libreswan on the CUDN network directly
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ipsec-vpn
  namespace: windows-non-prod
  labels:
    app: ipsec-vpn
    role: gateway
  annotations:
    description: "IPSec VPN gateway for windows-non-prod CUDN - replaces container VPN"
spec:
  running: true
  dataVolumeTemplates:
    - metadata:
        name: ipsec-vpn-root
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: gp3-csi
        source:
          registry:
            url: docker://quay.io/containerdisks/centos-stream:9
  template:
    metadata:
      labels:
        app: ipsec-vpn
        role: gateway
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: root
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            # Primary interface - pod network (for VPN tunnel egress to AWS TGW)
            - name: default
              masquerade: {}
            # Secondary interface - windows-non-prod CUDN (gateway at 10.227.128.1)
            - name: cudn
              bridge: {}
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 2
      networks:
        - name: default
          pod: {}
        - name: cudn
          multus:
            networkName: windows-non-prod
      volumes:
        - name: root
          dataVolume:
            name: ipsec-vpn-root
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: ipsec-vpn-cloudinit
---
# Cloud-init configuration for IPSec VPN Gateway VM
apiVersion: v1
kind: Secret
metadata:
  name: ipsec-vpn-cloudinit
  namespace: windows-non-prod
  annotations:
    description: "Cloud-init for IPSec VPN gateway VM with Libreswan"
type: Opaque
stringData:
  userdata: |
    #cloud-config
    # IPSec VPN Gateway VM Configuration
    # Runs Libreswan for IPSec tunnel termination on CUDN
    
    # Root password
    password: Canon123!
    chpasswd:
      expire: false
    ssh_pwauth: true
    
    # SSH keys
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILC4UQZlAjU0yNNNn9WypjpZbxUVr1Pu4x8Aiig405mK ipsec-vpn
    
    # Install required packages
    packages:
      - libreswan
      - iptables
      - iptables-services
      - tcpdump
      - net-tools
      - bind-utils
      - traceroute
      - vim
      - curl
      - wget
      - nmap
      - iperf3
    
    # System configuration for IPSec and routing
    bootcmd:
      - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.d/99-ipsec.conf
      - echo "net.ipv4.conf.all.rp_filter=0" >> /etc/sysctl.d/99-ipsec.conf
      - echo "net.ipv4.conf.default.rp_filter=0" >> /etc/sysctl.d/99-ipsec.conf
      - echo "net.ipv4.conf.all.accept_redirects=0" >> /etc/sysctl.d/99-ipsec.conf
      - echo "net.ipv4.conf.default.accept_redirects=0" >> /etc/sysctl.d/99-ipsec.conf
      - echo "net.ipv4.conf.all.send_redirects=0" >> /etc/sysctl.d/99-ipsec.conf
      - echo "net.ipv4.conf.default.send_redirects=0" >> /etc/sysctl.d/99-ipsec.conf
      - sysctl --system
    
    write_files:
      # Network configuration for eth1 (CUDN interface - gateway at 10.227.128.1)
      - path: /etc/NetworkManager/system-connections/eth1.nmconnection
        owner: root:root
        permissions: '0600'
        content: |
          [connection]
          id=eth1
          type=ethernet
          interface-name=eth1
          autoconnect=true
          
          [ipv4]
          method=manual
          address1=10.227.128.1/21
          may-fail=false
          
          [ipv6]
          method=disabled
      
      # IPSec configuration (ipsec.conf) - placeholder for actual VPN config
      - path: /etc/ipsec.d/aws-vpn.conf
        owner: root:root
        permissions: '0600'
        content: |
          # AWS Site-to-Site VPN Configuration
          # Will be replaced with actual configuration from existing site-to-site-vpn ConfigMap
          
          conn aws-vpn-tunnel1
              authby=secret
              auto=start
              dpdaction=restart
              dpddelay=10
              dpdtimeout=30
              ike=aes128-sha1-modp1024
              ikelifetime=28800s
              ikev2=no
              keyingtries=%forever
              left=%defaultroute
              leftid=<REPLACE_WITH_VPN_POD_NAT_IP>
              leftsubnet=10.227.128.0/21
              right=3.232.27.186
              rightsubnet=0.0.0.0/0
              type=tunnel
              phase2alg=aes128-sha1-modp1024
              lifetime=3600s
              keyexchange=ikev1
              
          conn aws-vpn-tunnel2
              authby=secret
              auto=start
              dpdaction=restart
              dpddelay=10
              dpdtimeout=30
              ike=aes128-sha1-modp1024
              ikelifetime=28800s
              ikev2=no
              keyingtries=%forever
              left=%defaultroute
              leftid=<REPLACE_WITH_VPN_POD_NAT_IP>
              leftsubnet=10.227.128.0/21
              right=98.94.136.2
              rightsubnet=0.0.0.0/0
              type=tunnel
              phase2alg=aes128-sha1-modp1024
              lifetime=3600s
              keyexchange=ikev1
      
      # IPSec secrets (ipsec.secrets) - placeholder
      - path: /etc/ipsec.d/aws-vpn.secrets
        owner: root:root
        permissions: '0600'
        content: |
          # AWS VPN Pre-Shared Keys
          # Will be replaced with actual secrets from site-to-site-vpn namespace
          <REPLACE_WITH_VPN_POD_NAT_IP> 3.232.27.186 : PSK "<TUNNEL1_PSK>"
          <REPLACE_WITH_VPN_POD_NAT_IP> 98.94.136.2 : PSK "<TUNNEL2_PSK>"
      
      # Gateway and IPSec configuration script
      - path: /usr/local/bin/configure-ipsec-gateway.sh
        owner: root:root
        permissions: '0755'
        content: |
          #!/bin/bash
          set -e
          
          echo "=========================================="
          echo "IPSec VPN Gateway Configuration"
          echo "=========================================="
          
          # Wait for interfaces
          for i in {1..30}; do
            if ip link show eth1 &>/dev/null; then
              echo "✓ eth1 (CUDN) interface found"
              break
            fi
            sleep 2
          done
          
          # Ensure eth1 has correct IP
          if ! ip addr show eth1 | grep -q "10.227.128.1/21"; then
            echo "Configuring eth1 IP address (10.227.128.1/21)..."
            ip addr flush dev eth1
            ip addr add 10.227.128.1/21 dev eth1
            ip link set eth1 up
          fi
          
          # Enable IP forwarding
          echo "Enabling IP forwarding..."
          sysctl -w net.ipv4.ip_forward=1
          sysctl -w net.ipv4.conf.all.rp_filter=0
          sysctl -w net.ipv4.conf.default.rp_filter=0
          
          # Stop firewalld (using iptables instead)
          systemctl stop firewalld 2>/dev/null || true
          systemctl disable firewalld 2>/dev/null || true
          
          # Configure iptables
          echo "Configuring iptables NAT and forwarding..."
          
          # Flush existing rules
          iptables -t nat -F
          iptables -F FORWARD
          
          # NAT for CUDN traffic going to external networks via eth0 (pod network)
          iptables -t nat -A POSTROUTING -s 10.227.128.0/21 ! -d 10.227.128.0/21 -o eth0 -j MASQUERADE
          
          # Allow forwarding from CUDN to pod network (outbound)
          iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT
          # Allow inbound from on-prem (VPN) to CUDN VMs - required for on-prem → VM (e.g. RDP)
          iptables -A FORWARD -i eth0 -o eth1 -d 10.227.128.0/21 -j ACCEPT
          # Allow return traffic for connections initiated from VMs
          iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
          
          # Allow VM-to-VM forwarding within CUDN
          iptables -A FORWARD -i eth1 -o eth1 -j ACCEPT
          
          # Drop invalid packets
          iptables -A FORWARD -m state --state INVALID -j DROP
          
          # Save iptables rules
          iptables-save > /etc/sysconfig/iptables
          
          # Enable iptables service
          systemctl enable iptables
          systemctl start iptables
          
          echo "✓ Routing and NAT configuration complete!"
          
          # Configure IPSec
          echo "Configuring Libreswan..."
          
          # Enable and start IPSec
          systemctl enable ipsec
          systemctl start ipsec
          
          # Wait for IPSec to be ready
          sleep 5
          
          # Load connections
          ipsec addconn aws-vpn-tunnel1 || true
          ipsec addconn aws-vpn-tunnel2 || true
          
          # Attempt to start tunnels
          ipsec up aws-vpn-tunnel1 || echo "⚠ Tunnel 1 not started (may need correct secrets)"
          ipsec up aws-vpn-tunnel2 || echo "⚠ Tunnel 2 not started (may need correct secrets)"
          
          echo ""
          echo "=== Status ==="
          echo "Hostname: $(hostname)"
          ip -br addr show
          echo ""
          echo "IP Forwarding: $(sysctl -n net.ipv4.ip_forward)"
          echo ""
          echo "IPSec Status:"
          ipsec status | head -20 || echo "IPSec not fully configured yet"
          echo "=========================================="
      
      # Status check script
      - path: /usr/local/bin/ipsec-status.sh
        owner: root:root
        permissions: '0755'
        content: |
          #!/bin/bash
          echo "=== IPSec VPN Gateway Status ==="
          echo "Hostname: $(hostname)"
          echo "Uptime: $(uptime -p)"
          echo ""
          echo "=== Network Interfaces ==="
          ip -br addr show
          echo ""
          echo "=== Routing Table ==="
          ip route show
          echo ""
          echo "=== IP Forwarding ==="
          sysctl net.ipv4.ip_forward
          echo ""
          echo "=== IPSec Status ==="
          ipsec status
          echo ""
          echo "=== NAT Rules ==="
          iptables -t nat -L POSTROUTING -n -v
          echo ""
          echo "=== Forwarding Rules ==="
          iptables -L FORWARD -n -v
          echo "=========================================="
    
    runcmd:
      # Reload NetworkManager to pick up eth1 config
      - sleep 5
      - nmcli connection reload
      - nmcli connection up eth1 || true
      
      # Run gateway and IPSec configuration
      - sleep 10
      - /usr/local/bin/configure-ipsec-gateway.sh | tee /var/log/ipsec-gateway-config.log
      
      # Create motd
      - |
        cat > /etc/motd <<'EOF'
        ==========================================
        IPSec VPN Gateway VM
        ==========================================
        Role: IPSec tunnel termination + gateway
        Gateway IP: 10.227.128.1/21 (CUDN)
        
        Commands:
          ipsec-status.sh      - Check VPN & gateway status
          ipsec status         - IPSec tunnel status
          ipsec restart        - Restart IPSec
          ip addr show         - Show interfaces
          iptables -t nat -L -n -v  - Show NAT rules
        
        Logs:
          /var/log/ipsec-gateway-config.log
          /var/log/pluto.log (IPSec)
        
        NEXT STEPS:
          1. Copy ipsec.conf from site-to-site-vpn ConfigMap
          2. Copy ipsec.secrets from site-to-site-vpn Secret
          3. Update leftid to match NAT IP
          4. Restart IPSec: systemctl restart ipsec
        ==========================================
        EOF
    
    final_message: |
      ==========================================
      IPSec VPN Gateway VM Ready
      ==========================================
      Gateway IP: 10.227.128.1/21 (CUDN)
      
      Configuration needed:
        - Copy VPN config from site-to-site-vpn namespace
        - Update ipsec.conf with correct NAT IP
        - Add ipsec.secrets with PSKs
      
      Run: ipsec-status.sh
      ==========================================
