---
# Example IPSec VM configuration - ipsec-a
# This VM establishes the IPSec tunnel and acts as a gateway
# Deploy a second VM (ipsec-b) in a different AZ for high availability
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ipsec-a
  namespace: vpn-infra
  labels:
    app: ipsec-gateway
    role: primary
  annotations:
    description: "Primary IPSec gateway VM for site-to-site VPN"
spec:
  running: true
  dataVolumeTemplates:
    - metadata:
        name: ipsec-a-root
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: gp3-csi  # Adjust to your storage class
        source:
          registry:
            # CentOS Stream 10 - adjust to RHEL or CentOS Stream 9 as needed
            url: docker://quay.io/containerdisks/centos-stream:10
  template:
    metadata:
      labels:
        app: ipsec-gateway
        role: primary
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: root
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            # Primary interface - pod network for egress and management
            - name: default
              masquerade: {}
            # Secondary interface - CUDN for VPN traffic and gateway routing
            - name: cudn
              bridge: {}
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 2
      # Node affinity to spread VMs across availability zones
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east-1a  # Change to your first AZ
      networks:
        - name: default
          pod: {}
        - name: cudn
          multus:
            networkName: vm-network-attachment
      volumes:
        - name: root
          dataVolume:
            name: ipsec-a-root
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: ipsec-vm-cloudinit
---
# Example IPSec VM configuration - ipsec-b
# Secondary VM for high availability in different AZ
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ipsec-b
  namespace: vpn-infra
  labels:
    app: ipsec-gateway
    role: secondary
  annotations:
    description: "Secondary IPSec gateway VM for high availability"
spec:
  running: true
  dataVolumeTemplates:
    - metadata:
        name: ipsec-b-root
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: gp3-csi  # Adjust to your storage class
        source:
          registry:
            url: docker://quay.io/containerdisks/centos-stream:10
  template:
    metadata:
      labels:
        app: ipsec-gateway
        role: secondary
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: root
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: cudn
              bridge: {}
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 2
      # Node affinity to different AZ than ipsec-a
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east-1b  # Change to your second AZ
      networks:
        - name: default
          pod: {}
        - name: cudn
          multus:
            networkName: vm-network-attachment
      volumes:
        - name: root
          dataVolume:
            name: ipsec-b-root
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: ipsec-vm-cloudinit
