---
# NetworkAttachmentDefinition for openshift-mtv namespace
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: windows-non-prod
  namespace: openshift-mtv
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    k8s.v1.cni.cncf.io/resourceName: openshift.io/windows-non-prod
  labels:
    app.kubernetes.io/component: network
    app.kubernetes.io/name: windows-non-prod
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ovn-k8s-cni-overlay",
      "name": "windows-non-prod",
      "netAttachDefName": "openshift-mtv/windows-non-prod",
      "subnets": "10.132.104.0/22",
      "mtu": 1400,
      "ipam": {
        "type": "whereabouts",
        "range": "10.132.104.0/22",
        "range_start": "10.132.104.4",
        "range_end": "10.132.107.254",
        "gateway": "10.132.104.1",
        "exclude": [
          "10.132.104.1/32",
          "10.132.104.2/32",
          "10.132.104.3/32",
          "10.132.104.10/32",
          "10.132.104.11/32",
          "10.132.104.19/32",
          "10.132.104.20/32",
          "10.132.104.21/32"
        ]
      }
    }

---
# NetworkAttachmentDefinition for vm-migrations namespace
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: windows-non-prod
  namespace: vm-migrations
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    k8s.v1.cni.cncf.io/resourceName: openshift.io/windows-non-prod
  labels:
    app.kubernetes.io/component: network
    app.kubernetes.io/name: windows-non-prod
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ovn-k8s-cni-overlay",
      "name": "windows-non-prod",
      "netAttachDefName": "vm-migrations/windows-non-prod",
      "subnets": "10.132.104.0/22",
      "mtu": 1400,
      "ipam": {
        "type": "whereabouts",
        "range": "10.132.104.0/22",
        "range_start": "10.132.104.4",
        "range_end": "10.132.107.254",
        "gateway": "10.132.104.1",
        "exclude": [
          "10.132.104.1/32",
          "10.132.104.2/32",
          "10.132.104.3/32",
          "10.132.104.10/32",
          "10.132.104.11/32",
          "10.132.104.19/32",
          "10.132.104.20/32",
          "10.132.104.21/32"
        ]
      }
    }

---
# NetworkAttachmentDefinition for windows-non-prod namespace
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: windows-non-prod
  namespace: windows-non-prod
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    k8s.v1.cni.cncf.io/resourceName: openshift.io/windows-non-prod
  labels:
    app.kubernetes.io/component: network
    app.kubernetes.io/name: windows-non-prod
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ovn-k8s-cni-overlay",
      "name": "windows-non-prod",
      "netAttachDefName": "windows-non-prod/windows-non-prod",
      "subnets": "10.132.104.0/22",
      "mtu": 1400,
      "ipam": {
        "type": "whereabouts",
        "range": "10.132.104.0/22",
        "range_start": "10.132.104.4",
        "range_end": "10.132.107.254",
        "gateway": "10.132.104.1",
        "exclude": [
          "10.132.104.1/32",
          "10.132.104.2/32",
          "10.132.104.3/32",
          "10.132.104.10/32",
          "10.132.104.11/32",
          "10.132.104.19/32",
          "10.132.104.20/32",
          "10.132.104.21/32"
        ]
      }
    }
