#------------------------------------------------------------------------------
# Cluster Admin Group Role Binding
# Purpose: Grant cluster-admin privileges to the cluster-admins group
# Managed via GitOps - changes should be made in the source repository
#------------------------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admins-group-binding
  labels:
    app.kubernetes.io/name: cluster-admin-group
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: gitops
    team: platform-engineering
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: cluster-admins
