---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cnv
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: "Namespace for OpenShift Virtualization Operator"
