---
# DevWorkspace Operator - installs to openshift-operators namespace
# Required by Web Terminal operator
# No additional namespace or OperatorGroup required
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devworkspace-operator
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: devworkspace-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
