---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-adp
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: "Namespace for OADP (OpenShift API for Data Protection)"
