---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-healthcheck-operator
  namespace: openshift-node-healthcheck-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: node-healthcheck-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
