---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-mtv
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/description: "Namespace for the Migration Toolkit for Virtualization Operator"
