---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: "https://argo-demo-320648.vault.azure.net/"
      tenantId: "332f003b-2800-41fc-8138-e0a30ca8ce07"
      authSecretRef:
        clientId:
          name: azure-keyvault-credentials
          namespace: external-secrets
          key: clientId
        clientSecret:
          name: azure-keyvault-credentials
          namespace: external-secrets
          key: clientSecret

