apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: mtv-target-network:k8s.cni.cncf.io/NetworkAttachmentDefinition:vm-migrations/windows-non-prod
    description: Secondary network for Windows VMs - 10.132.104.0/22
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br-windows
  creationTimestamp: "2026-02-10T18:43:16Z"
  generation: 2
  labels:
    app.kubernetes.io/component: mtv-network
    app.kubernetes.io/name: windows-non-prod
    cluster: rosa-non-prod
    environment: non-prod
    network.openshift.io/type: vm-migration
  name: windows-non-prod
  namespace: vm-migrations
  resourceVersion: "6419760"
  uid: 34a43834-5e65-4026-a910-0e7882f464a7
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "windows-non-prod",
      "type": "bridge",
      "bridge": "br-windows",
      "vlan": 101,
      "preserveDefaultVlan": false,
      "macspoofchk": true,
      "ipam": {
        "type": "whereabouts",
        "range": "10.132.104.0/22",
        "range_start": "10.132.104.10",
        "range_end": "10.132.107.250",
        "gateway": "10.132.104.1",
        "routes": [
          {
            "dst": "10.132.0.0/14",
            "gw": "10.132.104.1"
          },
          {
            "dst": "10.227.96.0/20",
            "gw": "10.132.104.1"
          }
        ],
        "exclude": [
          "10.132.104.1/32",
          "10.132.104.2/32",
          "10.132.104.3/32"
        ]
      }
    }
