---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-beyondtrust
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    beyondtrust:
      # Authentication - requires secret with API key
      auth:
        apiKey:
          secretRef:
            name: bt-apikey
            key: ApiKey
      
      # BeyondTrust Password Safe server configuration
      server:
        # API URL - update per environment
        apiUrl: https://nyaput18:443/BeyondTrust/api/public/v3/
        
        # Client timeout
        clientTimeOutSeconds: 45
        
        # Retrieval type (SECRET or MANAGED_ACCOUNT)
        retrievalType: SECRET
        
        # Verify CA certificate
        verifyCA: true
